apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: "namespace-value"
spec:
  type: NodePort
  selector:
    app: node
    tier: web
  ports:
    - port: 3000
      targetPort: 3000
